version: "3.9"

services:
  keycloak-psql:
    image: postgres:13
    restart: always
    env_file:
      - ./keycloak/.env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./keycloak/.env
    ports:
      - "8888:80"
    depends_on:
      - keycloak-psql

  keycloak:
    env_file:
      - ./keycloak/.env
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-psql

  mq:
    image: rabbitmq:3.12.10-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "mq_data:/data"

volumes:
  mq_data: